# Generated by Django 3.0.6 on 2020-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(choices=[('LS', 'Livestock'), ('GR', 'Grains'), ('CR', 'Cereal')], default='LS', max_length=2)),
                ('container', models.CharField(choices=[('RF', 'Refrigerated'), ('B', 'Basic')], default='RF', max_length=2)),
            ],
        ),
    ]
