# Generated by Django 3.0.6 on 2020-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryclass',
            name='cargo',
            field=models.CharField(choices=[('Livestock', 'Livestock'), ('Grains', 'Grains'), ('Cereal', 'Cereal')], default='LS', max_length=10),
        ),
        migrations.AlterField(
            model_name='inquiryclass',
            name='container',
            field=models.CharField(choices=[('Refrigerated', 'Refrigerated'), ('Basic', 'Basic')], default='RF', max_length=13),
        ),
    ]
