# Generated by Django 3.0.6 on 2020-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_auto_20200604_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryclass',
            name='cargo',
            field=models.CharField(choices=[('Livestock', 'Livestock'), ('Grains', 'Grains'), ('Cereal', 'Cereal')], default='Livestock', max_length=10),
        ),
        migrations.AlterField(
            model_name='inquiryclass',
            name='container',
            field=models.CharField(choices=[('Refrigerated', 'Refrigerated'), ('Basic', 'Basic')], default='Refrigerated', max_length=13),
        ),
    ]
